### ISSUE TITLE
Plugins fail to install

### ISSUE THREAD

**Issue by memelet** [alerta/docker-alerta#100]
version: 6.5.0

When specifying plugins via `INSTALL_PLUGINS` I get the following error. 

```
Installing plugin 'reject'
+ '[' -n '' ']'
+ IFS=,
+ for plugin in ${INSTALL_PLUGINS}
+ echo 'Installing plugin '\''reject'\'''
+ /venv/bin/pip install git+https://github.com/alerta/alerta-contrib.git#subdirectory=plugins/reject
The directory '/home/alerta/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/alerta/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/alerta/alerta-contrib.git#subdirectory=plugins/reject
  Cloning https://github.com/alerta/alerta-contrib.git to /tmp/pip-req-build-edsodrg2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/venv/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-edsodrg2/plugins/reject/setup.py'
    
    ----------------------------------------
```

**Comment by memelet** [comment]
Strange I changed the envs from
```
      - INSTALL_PLUGINS=reject,blackout,normalise,enhance
      - PLUGINS=reject,blackout,normalise,enhance
```
to
```
      - INSTALL_PLUGINS=normalise,enhance
#      - PLUGINS=reject,blackout,normalise,enhance
```
and now at least these install

```
+ for plugin in ${INSTALL_PLUGINS}
+ echo 'Installing plugin '\''normalise'\'''
+ /venv/bin/pip install git+https://github.com/alerta/alerta-contrib.git#subdirectory=plugins/normalise
Installing plugin 'normalise'
The directory '/home/alerta/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/alerta/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/alerta/alerta-contrib.git#subdirectory=plugins/normalise
  Cloning https://github.com/alerta/alerta-contrib.git to /tmp/pip-req-build-slbw9h35
Installing collected packages: alerta-normalise
  Running setup.py install for alerta-normalise: started
    Running setup.py install for alerta-normalise: finished with status 'done'
Successfully installed alerta-normalise-5.3.1
```

**Comment by satterly** [comment]
The `reject` and `blackout` plugins are built-in and don't need to be installed. Only those that need to be installed should be listed in `INSTALL_PLUGINS` environment variable.

**Comment by memelet** [comment]
Ok, thanks. It was unclear from docs what plugins are built in.
