### ISSUE TITLE
uwsgi -[Errno 13] Permission denied: '/alertad.log'

### ISSUE THREAD

**Issue by pad92** [alerta/docker-alerta#105]
with uwsgi try to log on /alertad.log

it's possible to send logs to stderr/stdout ?

```
2019-01-21 10:45:06,382 DEBG 'uwsgi' stdout output:
PermissionError: [Errno 13] Permission denied: '/alertad.log'
```

**Comment by satterly** [comment]
They go to stderr/stdout by default. Please share your config.

**Comment by pad92** [comment]
# my compose for alerta-web

```docker-compose
  alerta-web:
    image: alerta/alerta-web:latest
    env_file:
      - ./alerta/config
    depends_on:
      - alerta-db
    ports:
      - 8080:8080
    networks:
      - promnet
      - dbnet
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.enable=true"
      - "traefik.docker.network=prom_promnet"
      - "traefik.protocol=http"
      - "traefik.port=8080"
      - "traefik.backend=alerta"
      - "traefik.frontend.passHostHeader=True"
      - "traefik.frontend.rule=Host:1.2.3.4; PathPrefix:/alerta"
```
# alerta variables ( into ./alerta/config )
```
PLUGINS=blackout,prometheus,enhance
INSTALL_PLUGINS=prometheus,enhance
ALERTMANAGER_API_URL=http://alertmanager:9093
BASE_URL=/alerta/api
USE_PROXYFIX=True

DATABASE_URL=mongodb://alerta-db:27017/monitoring
AUTH_REQUIRED=True
ALLOWED_EMAIL_DOMAIN=alerta.io,otherdomain.tld
ADMIN_USERS=admin@alerta.io
ADMIN_PASSWORD=alerta
DEBUG=0
```
# uwsgi ini from running container

```ini
[uwsgi]
chdir = /
mount = /alerta/api=/app/wsgi.py
callable = app
manage-script-name = true

master = true
processes = 5

socket = /tmp/uwsgi.sock
buffer-size = 8192
chmod-socket = 664
uid = alerta
gid = alerta
vacuum = true

die-on-term = true
```
# container logs 

```+ RUN_ONCE=/app/.run_once
+ '[' '!' -f /web/config.json ']'
+ envsubst
+ '[' '!' -f /app/alertad.conf ']'
+ cat
++ head -c 32
++ tr -dc 'A-Za-z0-9_!@#$%^&*()-+='
+ '[' '!' -f /app/.run_once ']'
++ tr -s /
++ echo //alerta/api
+ BASE_PATH=/alerta/api
+ sed -i 's@!BASE_PATH!@/alerta/api@' /app/uwsgi.ini
+ sed -i 's@!BASE_PATH!@/alerta/api@' /app/nginx.conf
+ sed -i 's@!BASE_PATH!@/alerta/api@' /app/supervisord.conf
+ WEB_PATH=/alerta
+ sed -i 's@!WEB_PATH!@/alerta@' /app/nginx.conf
+ '[' -n admin@alerta.io ']'
+ alertad user --password alerta --all
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/config.py", line 565, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/lib/python3.6/logging/config.py", line 738, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/lib/python3.6/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/alertad.log'
...
```

I don't see what I missed.

**Comment by pad92** [comment]
@satterly 
I couldn't reproduce the outcome on another docker instance.
I think the problem is related to my environment and not directly to the image.

I'll get back to you as soon as I have more information.

**Comment by proffust** [comment]
I have same error
docker-compose.yml
```
version: "3"
services:
  alerta-web:
    image: alerta/alerta-web
    depends_on:
      - alerta-db
    environment:
      - DATABASE_URL=mongodb://alerta-db:27017/monitoring
      - AUTH_REQUIRED=False
      - PLUGINS=reject,blackout,normalise,enhance
      - BASE_URL=/alerta/api
    networks:
      - frontend
      - alerta-net
    restart: always

  alerta-db:
    image: mongo
    volumes:
      - /var/lib/docker/data/mongodb:/data/db
    networks:
      - alerta-net
    restart: always

```
in logs 
```
019-01-23 12:18:48,420 DEBG 'uwsgi' stdout output:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/config.py", line 565, in configure

2019-01-23 12:18:48,421 DEBG 'uwsgi' stdout output:
    handler = self.configure_handler(handlers[name])
  File "/usr/local/lib/python3.6/logging/config.py", line 738, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/lib/python3.6/logging/handlers.py", line 150, in __init__

2019-01-23 12:18:48,421 DEBG 'uwsgi' stdout output:
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1032, in __init__

2019-01-23 12:18:48,421 DEBG 'uwsgi' stdout output:
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1061, in _open

2019-01-23 12:18:48,421 DEBG 'uwsgi' stdout output:
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/alertad.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/wsgi.py", line 1, in <module>

2019-01-23 12:18:48,422 DEBG 'uwsgi' stdout output:
    from alerta import app
  File "/venv/lib/python3.6/site-packages/alerta/__init__.py", line 29, in <module>
    app = create_app()
  File "/venv/lib/python3.6/site-packages/alerta/app.py", line 47, in create_app
    logger.setup_logging(app)
  File "/venv/lib/python3.6/site-packages/alerta/utils/logging.py", line 81, in setup_logging

2019-01-23 12:18:48,422 DEBG 'uwsgi' stdout output:
    'handlers': app.config['LOG_HANDLERS']
  File "/usr/local/lib/python3.6/logging/config.py", line 802, in dictConfig

2019-01-23 12:18:48,422 DEBG 'uwsgi' stdout output:
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.6/logging/config.py", line 573, in configure

2019-01-23 12:18:48,422 DEBG 'uwsgi' stdout output:
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'file': [Errno 13] Permission denied: '/alertad.log'

2019-01-23 12:18:48,423 DEBG 'uwsgi' stdout output:
VACUUM: unix socket /tmp/uwsgi.sock removed.

```
root@p256i48vc-app03:~/prom# docker -v
Docker version 18.09.0, build 4d60db4

root@p256i48vc-app03:~/prom# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch

root@p256i48vc-app03:~/prom# docker-compose --version
docker-compose version 1.23.1, build b02f1306

**Comment by satterly** [comment]
Alerta 6.7.1  with this fix is now available on [Docker Hub](https://cloud.docker.com/u/alerta/repository/registry-1.docker.io/alerta/alerta-web/hub-builddetail/bvz5dyrbuvm3bcyqs3j2tte).

**Comment by pad92** [comment]
#108 for cleanup.
