### ISSUE TITLE
Command line options fail to run

### ISSUE THREAD

**Issue by callahan22** [alerta/docker-alerta#113]
**Describe the bug**
Running any of the command line options when exec'ed into a docker container fails with the same error messages.

**To Reproduce**
1. sudo docker exec -it alerta /bin/bash
2. Run 'alerta watch' or 'alerta top' or any other switch for alerta and the same error messages will be returned:
```
alerta@071c919c2588:/$ alerta watch
Traceback (most recent call last):
  File "/venv/bin/alerta", line 10, in <module>
    sys.exit(cli())
  File "/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.6/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/venv/lib/python3.6/site-packages/alertaclient/cli.py", line 54, in cli
    config.get_remote_config()
  File "/venv/lib/python3.6/site-packages/alertaclient/config.py", line 57, in get_remote_config
    remote_config = r.json()
  File "/venv/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Expected behavior**
A terminal view of the alerts or some other data back such as Uptime, etc.

**Desktop:**
 - OS: Ubuntu 18.04 - Docker 18.9.2

**Comment by satterly** [comment]
Thanks for raising the issue. Is this something you can fix?

**Comment by callahan22** [comment]
Honestly? Probably not. I'm no coder, more a tinkerer! I will take a look at it when I get some time though. Right now, I'm on a deadline for getting this Prometheus/Grafana/alerta plus all extras rolled out for work. :-)

**Comment by satterly** [comment]
No problem. It's unlikely to be looked at any time soon then. The work-around is the install the `alerta` client tool locally on your computer. It trivially easy... `pip install alerta`.

**Comment by satterly** [comment]
Not sure what changed but this works now ...

<img width="691" alt="Screenshot 2019-05-18 at 23 28 58" src="https://user-images.githubusercontent.com/615057/57975176-c1979b00-79c4-11e9-9f40-9c29153dfc21.png">
