### ISSUE TITLE
PLUGINS not defined when running docker compose

### ISSUE THREAD

**Issue by satterly** [alerta/docker-alerta#20]
```
c9b52479:docker-alerta nsatterl$ docker-compose up
Starting dockeralerta_db_1
Starting dockeralerta_web_1
Attaching to dockeralerta_db_1, dockeralerta_web_1
db_1   | 2017-01-17T09:26:01.712+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=76bfb95f2b4b
db_1   | 2017-01-17T09:26:01.712+0000 I CONTROL  [initandlisten] db version v3.4.1
db_1   | 2017-01-17T09:26:01.712+0000 I CONTROL  [initandlisten] git version: 5e103c4f5583e2566a45d740225dc250baacfbd7
db_1   | 2017-01-17T09:26:01.712+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
db_1   | 2017-01-17T09:26:01.712+0000 I CONTROL  [initandlisten] allocator: tcmalloc
db_1   | 2017-01-17T09:26:01.712+0000 I CONTROL  [initandlisten] modules: none
db_1   | 2017-01-17T09:26:01.712+0000 I CONTROL  [initandlisten] build environment:
db_1   | 2017-01-17T09:26:01.712+0000 I CONTROL  [initandlisten]     distmod: debian81
db_1   | 2017-01-17T09:26:01.712+0000 I CONTROL  [initandlisten]     distarch: x86_64
db_1   | 2017-01-17T09:26:01.712+0000 I CONTROL  [initandlisten]     target_arch: x86_64
db_1   | 2017-01-17T09:26:01.712+0000 I CONTROL  [initandlisten] options: {}
db_1   | 2017-01-17T09:26:01.715+0000 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
db_1   | 2017-01-17T09:26:01.722+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
db_1   | 2017-01-17T09:26:01.726+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
db_1   | 2017-01-17T09:26:01.728+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=486M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
db_1   | 2017-01-17T09:26:03.546+0000 I CONTROL  [initandlisten]
db_1   | 2017-01-17T09:26:03.547+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
db_1   | 2017-01-17T09:26:03.547+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
db_1   | 2017-01-17T09:26:03.547+0000 I CONTROL  [initandlisten]
web_1  | Traceback (most recent call last):
web_1  |   File "<string>", line 1, in <module>
web_1  | NameError: name 'PLUGINS' is not defined
db_1   | 2017-01-17T09:26:03.566+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
db_1   | 2017-01-17T09:26:03.568+0000 I NETWORK  [thread1] waiting for connections on port 27017
db_1   | 2017-01-17T09:26:04.412+0000 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
dockeralerta_web_1 exited with code 1
web_1  | Collecting git+https://github.com/alerta/alerta-contrib.git#subdirectory=plugins/geoip
web_1  |   Cloning https://github.com/alerta/alerta-contrib.git to /tmp/pip-xrYHeR-build
web_1  | fatal: unable to access 'https://github.com/alerta/alerta-contrib.git/': Could not resolve host: github.com
web_1  | Command "git clone -q https://github.com/alerta/alerta-contrib.git /tmp/pip-xrYHeR-build" failed with error code 128 in None
web_1  | Traceback (most recent call last):
web_1  |   File "<string>", line 1, in <module>
web_1  | NameError: name 'PLUGINS' is not defined
web_1  | Traceback (most recent call last):
web_1  |   File "<string>", line 1, in <module>
web_1  | NameError: name 'PLUGINS' is not defined
web_1  | Traceback (most recent call last):
web_1  |   File "<string>", line 1, in <module>
web_1  | NameError: name 'PLUGINS' is not defined
dockeralerta_web_1 exited with code 1
web_1  | Collecting git+https://github.com/alerta/alerta-contrib.git#subdirectory=plugins/geoip
web_1  |   Cloning https://github.com/alerta/alerta-contrib.git to /tmp/pip-xrYHeR-build
web_1  | fatal: unable to access 'https://github.com/alerta/alerta-contrib.git/': Could not resolve host: github.com
web_1  | Command "git clone -q https://github.com/alerta/alerta-contrib.git /tmp/pip-xrYHeR-build" failed with error code 128 in None
web_1  | Traceback (most recent call last):


DEBUG = True
web_1  |   File "<string>", line 1, in <module>
web_1  | NameError: name 'PLUGINS' is not defined
web_1  | Traceback (most recent call last):
web_1  |   File "<string>", line 1, in <module>
web_1  | NameError: name 'PLUGINS' is not defined
web_1  | Traceback (most recent call last):
web_1  |   File "<string>", line 1, in <module>
web_1  | NameError: name 'PLUGINS' is not defined
web_1  | Traceback (most recent call last):
web_1  |   File "<string>", line 1, in <module>
web_1  | NameError: name 'PLUGINS' is not defined
web_1  | Traceback (most recent call last):
web_1  |   File "<string>", line 1, in <module>
web_1  | NameError: name 'PLUGINS' is not defined
dockeralerta_web_1 exited with code 1
Killing dockeralerta_web_1 ... done
Killing dockeralerta_db_1 ... done
c9b52479:docker-alerta nsatterl$ vi config/alertad.conf.example
c9b52479:docker-alerta nsatterl$ docker-compose rm
Going to remove dockeralerta_web_1, dockeralerta_db_1
Are you sure? [yN] y
Removing dockeralerta_web_1 ... done
Removing dockeralerta_db_1 ... done
c9b52479:docker-alerta nsatterl$ docker-compose up
```

**Comment by satterly** [comment]
https://www.elastic.co/blog/elasticsearch-docker-plugin-management

**Comment by satterly** [comment]
This was a transient network error due to testing this on the train to work.
