### ISSUE TITLE
Alerta Docker error

### ISSUE THREAD

**Issue by pbuzulan** [alerta/docker-alerta#343]
**Issue Summary**

**Environment**
- OS: Linux
- API version: 8.6.3
- Deployment: Docker
- For self-hosted, WSGI environment: docker-compose with nginx
- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? No

There is no way to make it work with Docker.
config/config.json file:
```
{"endpoint": "/api"}
```

I tried first:

```version: '3.1'
services:
  web:
    image: alerta/alerta-web
    volumes:
      - $PWD/config/config.json:/web/config.json
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      # - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=user@example.com
      - ADMIN_PASSWORD=alerta # default is "alerta"
      - ADMIN_KEY=meo-meo  # assigned to first user in ADMIN_USERS
      - ADMIN_KEY_MAXAGE=500
      - PLUGINS=reject,blackout,normalise,enhance
    restart: always

  db:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
```

Output: 
```
http://localhost:8080/api/config - 502, Bad Gateway
```
Details:
```
web_1  | 2021-11-30 11:26:02,718 DEBG 'nginx' stdout output:
web_1  | ip=\- [\30/Nov/2021:11:26:02 +0000] "\GET /js/chunk-vendors.801521e6.js.map HTTP/1.1" \200 \3037978 "\-" "\Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
web_1  | /web | /js/chunk-vendors.801521e6.js.map | > GET /js/chunk-vendors.801521e6.js.map HTTP/1.1
web_1  | 
web_1  | 2021-11-30 11:26:02,744 DEBG 'nginx' stdout output:
web_1  | 2021/11/30 11:26:02 [error] 48#48: *3 connect() failed (111: Connection refused) while connecting to upstream, client: YY.YY.YY.YY, server: , request: "GET /api/config HTTP/1.1", upstream: "uwsgi://127.0.0.1:29000", host: "XX.XX.XX.XX:8080", referrer: "http://XX.XX.XX.XX:8080/"
web_1  | ip=\- [\30/Nov/2021:11:26:02 +0000] "\GET /api/config HTTP/1.1" \502 \559 "\http://XX.XX.XX.XX:8080/" "\Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
web_1  | /web | /api/config | > GET /api/config HTTP/1.1
```

Then I tried the example solution you provide, [Alerta Docker Nginx Example](https://github.com/alerta/docker-alerta/tree/master/examples/nginx)

Output:
```
npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/app/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/app/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/app/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /app/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /app/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /app/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Linux 4.15.0-121-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /app/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-30T10_55_30_117Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1
ERROR: Service 'webui' failed to build : Build failed

```

There is no way to make this work without spending time. I checked all the issues closed/opened and many of them complained about a similar issue.

**Comment by pbuzulan** [comment]
I found the following links reporting errors as well:
- https://beta.alerta.io/
- https://try.alerta.io/
- https://alerta-api.herokuapp.com/

I found many documentation links posted in different issues broken. Frustrating...

**Comment by oijkn** [comment]
In your `config.json` file try that : `{"endpoint": "http(s)://<server_ip>:<server_port>/api"}`

**Comment by satterly** [comment]
I would actually leave this out completely...
```
    volumes:
      - $PWD/config/config.json:/web/config.json
```

**Comment by pbuzulan** [comment]
@oijkn @satterly 
Tried both solutions, no luck...

**Comment by oijkn** [comment]
Can you `ls $PWD/config` directory and then `cat config.json` file ?
When you jump into the docker what is the content of `cat /web/config.json` ?

**Comment by jcollie** [comment]
Seeing the same problem.  Seems to be because uwsgi won't stay running.

**Comment by oijkn** [comment]
@jcollie Can you do the manipulations indicated in my previous post and tell me what you have please?

**Comment by satterly** [comment]
@jcollie can you share your docker config? are you running the latest version?

**Comment by satterly** [comment]
Please try the latest version of the docker image. version 8.6.4

**Comment by jcollie** [comment]
Also setting an environment variable UWSGI_LISTEN=128 fixed the problem for me.
